title: GRaM Workshop @ ICML 2024
description: ELLIS Workshop on Geometry-grounded Representation Learning and Generative Modeling
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
logo: /assets/img/bannerimg.png
image: /assets/img/bannerimg.png
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
